public enum EUpgradeName {
    MOVEMENT_SPEED,
    TRUCK_TIME_REDUCE,
    DOUBLE_TRUCK_CAPACITY,
    DOUBLE_SOIL_WATERED_TIME,
    CROP_GROW_FASTER,
    INCREASE_PRODUCT_PRICE,
    SHOP_SALE,
    SLOW_DOWN_ANIMAL_HUNGER,
    FASTER_ANIMAL_PRODUCT,
}